# -----------------------------
# Site settings
# -----------------------------
title: My Minimal Blog(no style, please!) # name of the site
author: Riccardo Graziosi # name of site's author
email: riccardo.graziosi97@gmail.com # email of site's author
url: "https://xrito-o.github.io"  # No trailing slash
baseurl: "/dailyblog"                   # The subfolder name, starts with /
description: # description of the site

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# -----------------------------
# Theme settings
# -----------------------------
remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "cd ~" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

# -----------------------------
# Sass settings
# -----------------------------
sass:
  style: compressed

# -----------------------------
# Plugins
# -----------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex
  - jekyll-sitemap

# -----------------------------
# Jektex settings
# -----------------------------
jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

# -----------------------------
# Lunr search settings
# -----------------------------
lunr_search:
  exclude: [archive.md, about.md] # pages to skip
  fields: 
    title: 10
    content: 5
    categories: 5
    tags: 5

# -----------------------------
# Collections
# -----------------------------
collections:
  reco:
    output: true

# -----------------------------
# Syntax highlighting
# -----------------------------
highlighter: rouge

# -----------------------------
# Exclude folders
# -----------------------------
exclude:
  - vendor/
  - .jektex-cache/